// Auto-generated by PushToSite.bat - do not edit
var honorPhotos = [
  {
    "src": "assets/rongyuqiang/202510任以沐荣获成都七中八一学校体育艺术节200米第一名.jpg",
    "title": "任以沐荣获成都七中八一学校体育艺术节200米第一名",
    "year": "2025",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202510任以沐荣获成都七中八一学校体育艺术节冠军奖牌.jpg",
    "title": "任以沐荣获成都七中八一学校体育艺术节冠军奖牌",
    "year": "2025",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/20250321任以沐荣获成都七中八一学校国防教育优秀学员.jpg",
    "title": "任以沐荣获成都七中八一学校国防教育优秀学员",
    "year": "2025",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202405任以沐荣获成都七中八一学校红领巾奖章小主人章.jpg",
    "title": "任以沐荣获成都七中八一学校红领巾奖章小主人章",
    "year": "2024",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/20240404任以沐荣获袁隆平杂交水稻科学园研学证书.jpg",
    "title": "任以沐荣获袁隆平杂交水稻科学园研学证书",
    "year": "2024",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/20240314任以沐荣获成都七中八一学校科普童行科创未来小小金话筒.jpg",
    "title": "任以沐荣获成都七中八一学校科普童行科创未来小小金话筒",
    "year": "2024",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202310任以沐荣获成都市红领巾乡村学院劳动实践活动证明.jpg",
    "title": "任以沐荣获成都市红领巾乡村学院劳动实践活动证明",
    "year": "2023",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202306任以沐荣获双流中学九江实验学校学习二十大争做好少年一等奖.jpg",
    "title": "任以沐荣获双流中学九江实验学校学习二十大争做好少年一等奖",
    "year": "2023",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/20230514任以沐荣获四川广播电视台闪亮小主播实践证书.jpg",
    "title": "任以沐荣获四川广播电视台闪亮小主播实践证书",
    "year": "2023",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202305任以沐荣获成都市双流区512护士节征文绘画比赛优秀奖.jpg",
    "title": "任以沐荣获成都市双流区512护士节征文绘画比赛优秀奖",
    "year": "2023",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/202305任以沐荣获童心向党六一文艺汇演实践证明.jpg",
    "title": "任以沐荣获童心向党六一文艺汇演实践证明",
    "year": "2023",
    "unit": "",
    "detail": ""
  },
  {
    "src": "assets/rongyuqiang/2023任以沐美术作品星星火炬代代相传.jpg",
    "title": "任以沐美术作品星星火炬代代相传",
    "year": "2023",
    "unit": "",
    "detail": ""
  }
];
